/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author UCR
 */
public class ButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        initComponents();
    }
    public void listen (ActionListener controller)
    {
        this.btnConsult.addActionListener(controller);
        this.btnCreate.addActionListener(controller);
        this.btnExit.addActionListener(controller);
        this.btnModify.addActionListener(controller);
    }
    
    public void ofM ()
    {
        this.btnModify.enableInputMethods(false);
    }
    
    public void onM ()
    {   
        this.btnModify.enableInputMethods(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnConsult = new javax.swing.JButton();

        setOpaque(false);

        btnCreate.setBackground(new java.awt.Color(101, 110, 211));
        btnCreate.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(175, 179, 255));
        btnCreate.setText("Create");

        btnModify.setBackground(new java.awt.Color(101, 110, 211));
        btnModify.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnModify.setForeground(new java.awt.Color(175, 179, 255));
        btnModify.setText("Modify");

        btnExit.setBackground(new java.awt.Color(101, 110, 211));
        btnExit.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnExit.setForeground(new java.awt.Color(175, 179, 255));
        btnExit.setText("Exit");

        btnConsult.setBackground(new java.awt.Color(101, 110, 211));
        btnConsult.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnConsult.setForeground(new java.awt.Color(175, 179, 255));
        btnConsult.setText("Consult");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    // End of variables declaration//GEN-END:variables
}
