/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author alehe
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public void listen(ActionListener controller) {
        this.MiExit.addActionListener(controller);
        this.MiActivities.addActionListener(controller);
        this.MiUser.addActionListener(controller);
        this.MiPrograms.addActionListener(controller);
        this.MiReminders.addActionListener(controller);
        this.MiReports.addActionListener(controller);
        this.MiStudents.addActionListener(controller);
        this.MiTeachers.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MiActivities = new javax.swing.JMenuItem();
        MiUser = new javax.swing.JMenuItem();
        MiStudents = new javax.swing.JMenuItem();
        MiTeachers = new javax.swing.JMenuItem();
        MiReminders = new javax.swing.JMenuItem();
        MiPrograms = new javax.swing.JMenuItem();
        MiReports = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        MiExit.setText("Exit");
        jMenu1.add(MiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        MiActivities.setText("Activities");
        jMenu2.add(MiActivities);

        MiUser.setText("User");
        jMenu2.add(MiUser);

        MiStudents.setText("Students");
        jMenu2.add(MiStudents);

        MiTeachers.setText("Teachers");
        jMenu2.add(MiTeachers);

        MiReminders.setText("Reminders");
        jMenu2.add(MiReminders);

        MiPrograms.setText("Programs");
        jMenu2.add(MiPrograms);

        MiReports.setText("Reports");
        jMenu2.add(MiReports);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiActivities;
    private javax.swing.JMenuItem MiExit;
    private javax.swing.JMenuItem MiPrograms;
    private javax.swing.JMenuItem MiReminders;
    private javax.swing.JMenuItem MiReports;
    private javax.swing.JMenuItem MiStudents;
    private javax.swing.JMenuItem MiTeachers;
    private javax.swing.JMenuItem MiUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
