/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import modelo.Plan;


/**
 *
 * @author alehe
 */
public class PlanGUI extends javax.swing.JFrame {

    /**
     * Creates new form PlanGUI
     */
    public PlanGUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public ButtonPanel getButtonPanel() {
        return buttonPanel1;
    }

    public String getTextId() {
        return this.txtId.getText();
    }

     public Plan getPlan() {
        int id = Integer.parseInt(this.txtId.getText());
        String valid = this.txtValid.getText();
        String approval = this.txtApproval.getText();
        String description = this.txaDescription.getText();
        int credits = Integer.parseInt(this.txtCredits.getText());
        int carrera = Integer.parseInt(this.txtCode.getText());

        // Convertir las cadenas de fecha a LocalDate
        LocalDate validDate = stringToLocalDate(valid);
        LocalDate approvalDate = stringToLocalDate(approval);

        // Crear y retornar una nueva instancia de Plan
        return new Plan(id, validDate, description, credits, approvalDate,carrera );
    }

    private LocalDate stringToLocalDate(String dateString) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        try {
            return LocalDate.parse(dateString, formatter);
        } catch (DateTimeParseException e) {
            // Manejo de la excepción si el formato de la fecha es incorrecto
            System.err.println("Formato de fecha incorrecto: " + dateString);
            return null;
        }
    }
private String localDateToString(LocalDate date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return date != null ? date.format(formatter) : "";
    }
      public void setPlan(Plan plan) {
        this.txtId.setText(String.valueOf(plan.getId()));
        this.txaDescription.setText(plan.getDescription());
        this.txtCredits.setText(String.valueOf(plan.getCredits()));
        this.txtApproval.setText(localDateToString(plan.getEndDate()));
        this.txtValid.setText(localDateToString(plan.getStartDate()));
        this.txtCode.setText(String.valueOf(plan.getCarrera()));
    }

    public void clean() {
        this.txtId.setText("");
        this.txtApproval.setText("");
        this.txaDescription.setText("");
        this.txtCredits.setText("");
        this.txtValid.setText("");
        this.txtCode.setText("");
    }

    public boolean emply() {
        boolean emply = false;
        if (txtApproval.getText().isEmpty()) {
            emply = true;
        }
        if (txaDescription.getText().isEmpty()) {
            emply = true;
        }
        if (txtCredits.getText().isEmpty()) {
            emply = true;
        }
        if (txtValid.getText().isEmpty()) {
            emply = true;
        }
        if (txtId.getText().isEmpty()) {
            emply = true;
        }

        return emply;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApproval = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        buttonPanel1 = new view.ButtonPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel1.setText("Description:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txaDescription.setBackground(new java.awt.Color(235, 239, 255));
        txaDescription.setColumns(20);
        txaDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaDescription.setRows(5);
        txaDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        jScrollPane1.setViewportView(txaDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, -1));

        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel2.setText("Credits:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txtCredits.setBackground(new java.awt.Color(235, 239, 255));
        txtCredits.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCredits.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        getContentPane().add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, 30));

        jLabel3.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel3.setText("Approval date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txtApproval.setBackground(new java.awt.Color(235, 239, 255));
        txtApproval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApproval.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        getContentPane().add(txtApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 280, 30));

        jLabel4.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel4.setText("Valid date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        txtValid.setBackground(new java.awt.Color(235, 239, 255));
        txtValid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        getContentPane().add(txtValid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 280, 30));

        jLabel5.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txtId.setBackground(new java.awt.Color(235, 239, 255));
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 30));
        getContentPane().add(buttonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        jLabel6.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabel6.setText("Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtCode.setBackground(new java.awt.Color(235, 239, 255));
        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 110, 211), 3, true));
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, 30));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setText("Study Plan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 100, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 120, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 2.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 160, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Other 07reg.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 250, -1));

        jLabel9.setBackground(new java.awt.Color(235, 239, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.ButtonPanel buttonPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextField txtApproval;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtValid;
    // End of variables declaration//GEN-END:variables
}
